name: Update website

on:
  push:
    branches:
      - sphinx

jobs:
  build:
    strategy:
      matrix:
        language: [en, ca]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install requirements
      run: python -m pip install -r sphinx_source/requirements.txt
    - name: Build documentation
      run: |
        export WEBSITE_LANGUAGE=${{ matrix.language }}
        python -m sphinx sphinx_source website -b html -D language=${{ matrix.language}}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: sphinx-build
        publish_dir: ./website
        destination_dir: ${{ matrix.language }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
